### ISSUE TITLE
Register Button functioning 

### ISSUE THREAD

**Issue by savagecarol** [kossiitkgp/kwoc-bugs#35]
step 1 : if you created a account from register .
step 2 : if you logout after creation.
step 3: if you again click on register (it will directly login you it will not give you another registration form).

##  it started working as login button .
so now after that you cannot create one more account . (because registeration button is not working as it should work)

**Comment by sahil-shubham** [comment]
Similar to  #36 in a way

Why would you as an user want to register multiple accounts on the same device? For you to be able to do so you would need to go into incognito and try registering again, which would take you to GitHub login. This isn't a bug, it's just GitHub skipping the oauth step again because permission has been given to KWoC.

Closing this issue, thanks for reporting.
